language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: HCcyTLSiORx432WFfugtj8MYiJMpXl68CYVd9tLFFRUee/p1C2dotbZt7HOLVacU1qXnXE2GdTzqq73sWoodOUi5ppFPcw4mBAIe1HqxUkeAhvlz0i6kHtuXwJfGHFVhJnzCL3ek6zn2XJOb9Rlgn58eycSDmsnTH6B0JQzZXItEd3EqsxKi6y2yf4Jt73MfQ6b3GJzhOqAXpNbBMjSDYtVYNnNQMSzqW0XebPfx6/QDPDD9xLpZZWVbVvQVHQ+WcEaZPEY1LUDz7YnHEPbUOn5D8RrC0iZBpPBs+iupzLmh3C1vDf05GBgj5K9Mo16cgx+/RmPuWpyl31RkxuBkcgVn7tjL3CNWNa4w8C+dPKAeZlsAu6PEA1Asisw0TFowsGGzPpD1Pi62/So2ANU3gp9y0KJNIhK3sMo3OjqiGWRk1RDDYVwwy6pv1+dJkPdELkxKuuAsT+FXbKo2MqZGsSS/vyY1EP78ffE/Wt+9ztNl7Ub5s0PfT4wiuTh786HJ1Q1RE/L6xAjx2qQ4W5CLy/0FFSmHjIaSw0ZHQcYjoXDJwSEJtFo1PEfR6J10x7MIM2rmAQCK6DFfpzzk4YTCF3FxyqV9nZIj6YnUb54brfysnBfZ0XJusE3fXAgYobV0iR9j6dYBTNSWyAIzWqXaii3wOfeWT1NHmEp2ZcmRKdo=
  app: murmuring-coast-85604
  on:
    repo: anupamadh/mymdb-mongo
